import { StyleSheet, Platform } from 'react-native';

const barHeight = 0;

export const colors = {
  button: '#00B5B8',
  white: '#ffffff',
  placeholder: '#7F7F7F',
  textInput: '#B1B1B1',
  darkGray: '#888888',
  lightGray: '#DDDDDD',
  blackBackground: '#5D5D5D',
  lightBackground: '#E8E8E8',
  grayBackground: '#C8C8C8',
  lightBlackText: '#393939',
  blackText: '#000000',
  listItemBorder: '#A7A7A7',
  modalBackground: '#00000055',
  dialogBackground: '#555555E0',
  autocompleteBackground: '#F5F5F5EE',
  statusYellow: '#b99112',
  statusGreen: '#39a833',
  statusRed: '#EE2222',
  toastContainer: '#00B5B877',
  toastError: '#FF000099',
};

export const common = StyleSheet.create({
  rootContainer: {
    flex: 1,
    backgroundColor: colors.blackBackground,
  },
  sceneContainer: {
    flex: 1,
  },
  radialGradient: {
    position: 'absolute',
    top: '10%',
    right: 0,
    left: 0,
    bottom: 0,
    opacity: 0.3,
  },
  modalContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.modalBackground,
  },
  backgroundBottomContainerGray: {
    flex: 1,
    position: 'absolute',
    justifyContent: 'flex-end',
    backgroundColor: colors.grayBackground,
    bottom: 0,
    top: 0,
    right: 0,
    left: 0,
  },
  backgroundBottomContainerLight: {
    flex: 1,
    position: 'absolute',
    justifyContent: 'flex-end',
    backgroundColor: colors.lightBackground,
    bottom: 0,
    top: 0,
    right: 0,
    left: 0,
  },
  backgroundBottomImage: {
    aspectRatio: 1,
  },
});

export const component = StyleSheet.create({
  buttonContainer: {
    backgroundColor: colors.button,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 6,
    maxWidth: '45%',
    alignSelf: 'center',
  },
  buttonText: {
    color: colors.white,
    textAlign: 'center',
    fontSize: 15,
    flex: 1,
  },
  buttonGray: {
    backgroundColor: colors.darkGray,
  },
  textInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
    minHeight: 28, // for ios
    borderBottomWidth: 1,
    borderColor: colors.textInput,
  },
  textInputText: {
    flex: 1,
    padding: 0,
    paddingHorizontal: 15,
    fontSize: 16,
    color: 'black',
  },
  integerInputText: {
    textAlign: 'center',
    flex: undefined,
    paddingHorizontal: 7,
  },
  textInputHintText: {
    padding: 0,
    marginBottom: -3,
    alignSelf: 'flex-start',
    color: colors.placeholder,
    fontSize: 12,
    paddingHorizontal: 15,
  },
  textInputLeftIcon: {
    fontSize: 19,
    marginRight: -10,
    marginLeft: 15,
    color: colors.button,
  },
  textInputButtonContainer: {
    paddingVertical: 2,
    paddingHorizontal: 10,
    maxWidth: undefined,
    borderRadius: 8,
    margin: 2,
  },
  textInputButtonText: {
    flex: undefined,
    fontSize: 13,
  },

  headerContainer: {
    padding: 15,
    marginBottom: 5,
    minHeight: 54,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  headerText: {
    flex: 1,
    fontSize: 20,
    alignSelf: 'center',
    textAlign: 'center',
    color: colors.blackText,
  },
  headerTextMenu: {
    flex: 1,
    marginTop: -8,
    fontSize: 20,
    alignSelf: 'center',
    textAlign: 'center',
    color: colors.blackText,
  },
  subHeaderTextMenu: {
    flex: 1,
    marginBottom: -17,
    fontSize: 12,
    alignSelf: 'center',
    textAlign: 'center',
    color: colors.button,
    backgroundColor: 'transparent',
  },
  headerLeftButton: {
    padding: 10,
    position: 'absolute',
    left: 10,
    top: 0,
    zIndex: 1,
  },
  headerRightButton: {
    padding: 10,
    position: 'absolute',
    right: 10,
    top: 0,
    zIndex: 1,
  },
  headerAdditionRightButton: {
    padding: 10,
    position: 'absolute',
    right: 60,
    top: 0,
    zIndex: 1,
  },
  headerCircleButton: {
    height: 34,
    width: 34,
    borderWidth: 1,
    borderRadius: 17,
    borderColor: colors.button,
    justifyContent: 'center',
    alignItems: 'center',
  },

  listItemButtonContainer: {
    minHeight: 52,
    paddingHorizontal: 10,
    paddingVertical: 3,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderColor: colors.listItemBorder,
  },
  listItemButtonInfoContainer: {
    minHeight: 40,
    paddingHorizontal: 10,
    paddingVertical: 3,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderColor: colors.listItemBorder,
  },
  listItemMainText: {
    fontSize: 17,
    color: colors.blackText,
  },
  listItemText: {
    fontSize: 17,
    color: colors.lightBlackText,
  },
  listItemSubText: {
    fontSize: 12,
    color: colors.placeholder,
    paddingVertical: 3,
  },
  listItemDarkSubText: {
    fontSize: 13,
    color: colors.lightBlackText,
    paddingVertical: 3,
  },
  blockListItemDarkSubText: {
    paddingVertical: 3,
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
  },
  dropDownTextContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },

  menuContainer: {
    marginTop: barHeight,
    backgroundColor: colors.white,
    justifyContent: 'flex-start',
    flex: 1,
  },
  menuHeader: {
    padding: 15,
    height: 54,
    flexDirection: 'row',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 1,
    backgroundColor: colors.white,
    elevation: 5,
  },
  menuItemContainerWrapper: {
    paddingLeft: 36,
    paddingRight: 36,
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  menuMainContainer: {
    flex: 1,
  },
  menuContainerBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 143,
  },
  menuContainerBackgroundImage: {
    flex: 1,
  },
  menuLogoImage: {
    height: 68,
    alignSelf: 'center',
    marginTop: 26,
    marginBottom: 24,
  },
  menuItemContainer: {
    flex: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    borderWidth: 1,
    borderColor: '#ddd',
    shadowRadius: 1,
    borderRadius: 3,
    backgroundColor: colors.white,
    elevation: 5,
    zIndex: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
    padding: 14,
  },
  menuItemContainerText: {
    marginTop: 7,
    fontSize: 16,
    alignSelf: 'center',
    textAlign: 'center',
    color: colors.blackText,
  },
  menuItemText: {
    color: colors.white,
    fontSize: 18,
    alignSelf: 'center',
    padding: 15,
  },
  menuBadge: {
    position: 'absolute',
    zIndex: 6,
    elevation: 6,
    top: -5,
    right: -5,
    backgroundColor: colors.statusRed,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 30,
    padding: 5,
    borderRadius: 16,
  },
  menuBadgeText: {
    color: colors.white,
    fontSize: 13,
  },

  modalDialogContainer: {
    width: '70%',
    maxWidth: 500,
    backgroundColor: colors.dialogBackground,
    alignItems: 'center',
    borderRadius: 10,
    padding: 20,
  },
  modalDialogText: {
    color: colors.white,
    fontSize: 18,
    textAlign: 'center',
  },
  modalDialogButtonsBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
    width: '100%',
  },
  errorDialogText: {
    width: '100%',
    color: colors.white,
    paddingVertical: 10,
    marginBottom: 15,
  },
  errorDialogButtonsBar: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  toastContainer: {
    padding: 10,
    position: 'absolute',
    bottom: 0, // height: 50,
    left: 0,
    right: 0,
    backgroundColor: colors.toastContainer,
  },
  toastTitleText: {
    fontSize: 16,
    color: colors.white,
    alignSelf: 'center',
    textAlign: 'center',
  },
  toastMessageText: {
    color: colors.white,
    alignSelf: 'center',
    textAlign: 'center',
  },
  hideToastButton: {
    position: 'absolute',
    alignSelf: 'center',
    top: -15,
    right: -15,
    padding: 20,
  },

  loaderText: {
    fontSize: 16,
    color: colors.white,
    marginBottom: 15,
  },

  autocompleteRootContainer: {
    flex: 1,
    padding: 20,
    backgroundColor: colors.modalBackground,
    justifyContent: 'center',
    alignItems: 'center',
  },
  autocompleteContainer: {
    flex: 1,
    maxHeight: 400,
    maxWidth: 500,
    width: '100%',
    backgroundColor: colors.autocompleteBackground,
    paddingBottom: 10,
  },
  autocompleteInput: {
    marginHorizontal: 20,
    borderColor: colors.blackText,
  },
  autocompleteItemsContainer: {
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  autocompleteItem: {
    color: colors.lightBlackText,
    padding: 7,
  },
  inputDialogContainer: {
    backgroundColor: colors.autocompleteBackground,
    paddingBottom: 20,
  },

  filterContainer: {
    backgroundColor: colors.autocompleteBackground,
  },
  filterBodyContainer: {
    paddingHorizontal: 25,
    paddingBottom: 15,
  },
  filterHint: {
    fontSize: 17,
    color: colors.blackText,
    alignSelf: 'center',
    marginBottom: 5,
  },
  filterRow: {
    backgroundColor: colors.autocompleteBackground,
    paddingTop: 3,
    paddingHorizontal: 10,
    marginHorizontal: -10,
    marginBottom: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },

  cameraContainer: {
    flex: 1,
  },
  camera: {
    flex: 1,
    justifyContent: 'flex-end',
    padding: 20,
    backgroundColor: colors.black,
  },
  cameraButtonsBar: {
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
  },
  cameraButton: {
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    width: 60,
    height: 60,
  },
  cameraSmallButton: {
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 18,
    width: 36,
    height: 36,
    opacity: 0.9,
  },
  galleryView: {
    height: 140,
  },
  gallerySmallView: {
    height: 96,
  },
  galleryContainer: {
    flexGrow: 1,
    flexDirection: 'row',
    padding: 3,
    alignItems: 'center',
  },
  galleryImage: {
    height: 128,
    width: 128,
    margin: 3,
  },
  gallerySmallImage: {
    height: 84,
    width: 84,
    margin: 3,
  },

  imageCheckIndicator: {
    position: 'absolute',
    zIndex: 1,
    right: 10,
    top: 10,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#0004',
    borderWidth: 2,
    borderColor: '#EEE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeAccountButton: {
    right: -25,
  },
  removePartButton: {
    position: undefined,
    top: undefined,
    right: undefined,
    marginLeft: 5,
    marginRight: -5,
  },

  removePartContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },

  partListCountContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 5,
  },
  partListCountLabel: {
    color: 'black',
    minWidth: 20,
    textAlign: 'center',
  },

  usedPartsDialogQuantityLabel: {
    textAlign: 'center',
    fontSize: 20,
    color: 'black',
    minWidth: 50,
  },
  switchButton: {
    transform: Platform.select({
      ios: [{ scaleX: 0.75 }, { scaleY: 0.75 }],
      android: [{ scaleX: 0.9 }, { scaleY: 0.9 }],
    }),
  },

  thumbnailPasswordMain: {
    flex: 1,
    flexDirection: 'column',
  },

  thumbnailPasswordHintText: {
    padding: 0,
    alignSelf: 'flex-start',
    color: colors.placeholder,
    fontSize: 16,
    paddingHorizontal: 15,
    paddingTop: 15,
    paddingBottom: 8,
  },

  thumbnailPasswordContainer: {
    flex: 1,
    flexDirection: 'column',
    paddingBottom: 8,
    marginBottom: 8,
    borderBottomWidth: 1,
    borderColor: colors.textInput,
    borderStyle: 'solid',
  },

  thumbnailPasswordItems: {
    flex: 1,
    flexDirection: 'row',
    padding: 10,
    justifyContent: 'space-around',
  },

  thumbnailPasswordItem: {
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    borderWidth: 1,
    borderColor: colors.button,
    borderStyle: 'solid',
  },

  thumbnailPasswordItemText: {
    color: colors.white,
  },

  thumbnailPasswordItemActive: {
    backgroundColor: colors.button,
  },

  textInfoWrapper: {
    minHeight: 40,
    paddingHorizontal: 15,
    paddingTop: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderColor: colors.listItemBorder,
    marginBottom: 5,
  },

  textInfoTitle: {
    fontSize: 12,
    color: colors.placeholder,
    paddingVertical: 3,
  },

  textInfoTitleEmpty: {
    fontSize: 16,
    paddingBottom: 0,
  },

  textInfoText: {
    fontSize: 17,
    color: colors.blackText,
    paddingBottom: 10,
  },

  textInfoTextEmpty: {
    height: 0,
    paddingBottom: 0,
  },
  modalContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalWindow: {
    backgroundColor: 'white',
    paddingTop: 35,
    paddingHorizontal: 30,
    paddingBottom: 35,
    borderRadius: 8,
    width: 500,
    height: 500,
  },
  closeButton: {
    backgroundColor: 'transparent',
    marginBottom: 10,
    alignSelf: 'flex-end',
    width: 32,
    height: 32,
  },
  innerCloseButton: {
    marginTop: -5,
    width: 34,
    height: 34,
    alignSelf: 'flex-end',
    backgroundColor: 'transparent',
  },
});

export const scene = StyleSheet.create({
  splashLogoContainer: {
    height: '70%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  splashLogoImage: {
    width: '45%',
  },

  loginLogoImage: {
    width: '45%',
    maxWidth: 300,
    maxHeight: 150,
    alignSelf: 'center',
  },
  loginFormsContainer: {
    alignSelf: 'center',
    paddingHorizontal: 30,
    alignItems: 'center',
    justifyContent: 'center',
    maxWidth: 400,
    width: '100%',
  },

  searchInputContainer: {
    marginHorizontal: 35,
    marginVertical: 20,
  },
  listItemsContainer: {
    paddingHorizontal: 30,
    paddingVertical: 10,
  },
  innerListItemsContainer: {
    paddingVertical: 5,
  },
  listItemSpaceBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },

  orderTotalStatusText: {
    marginTop: 15,
    paddingHorizontal: 10,
    fontSize: 18,
    color: colors.blackText,
  },

  closeButton: {
    zIndex: 1,
    position: 'absolute',
    top: 20,
    right: 20,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#0005',
    justifyContent: 'center',
    alignItems: 'center',
  },

  responsiveWrapper: {
    width: '100%',
    alignItems: 'center',
  },
  responsive: {
    width: '100%',
    maxWidth: 500,
  },
  buttonSize: {
    marginBottom: 50,
    marginTop: 10,
  },
  cashiersHeader: {
    height: '10%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cashiersButton: {
    height: '90%',
    flex: 0.35,
    maxWidth: '100%',
    backgroundColor: '#00B5B9',
    borderRadius: 5,
    marginLeft: 15,
  },
  cashButton: {
    alignSelf: 'flex-start',
    height: '85%',
    flex: 0.18,
    borderRadius: 5,
    backgroundColor: '#25E566',
    marginRight: 10,
  },
  logoutButton: {
    alignSelf: 'flex-start',
    height: '85%',
    flex: 0.18,
    borderRadius: 5,
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#333333',
  },
  input: {
    height: '85%',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E7E7E9',
    borderRadius: 5,
  },
  inputLabel: {
    color: '#575F6E',
    fontWeight: '400',
    fontSize: 14,
  },
  selectLabel: {
    marginLeft: '3.5%',
    fontSize: 16,
    color: '#575F6E',
    fontWeight: '400',
  },
  select: {
    width: 290,
    height: 50,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E7E7E9',
    borderRadius: 5,
    marginTop: 5,
    marginRight: 20,
  },
  cashierLabel: {
    position: 'absolute',
    top: '-5%',
    right: 5,
    fontSize: 13,
    fontWeight: '500',
  },
  cashierLabelItem: {
    marginLeft: 10,
  },
  cashiersTable: {
    marginTop: 20,
    backgroundColor: 'white',
    maxHeight: '100%',
    borderRadius: 8,
    paddingTop: 19,
    overflow: 'hidden',
  },
  tableTitle: {
    color: '#575F6E',
    lineHeight: 18,
    fontSize: 14,
  },
  tableRow: {
    paddingLeft: 10,
    paddingRight: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    height: 61,
    borderBottomWidth: 1,
    borderBottomColor: '#E7E7E9',
  },
  tableFooterRow: {
    paddingLeft: 10,
    paddingRight: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    height: 54,
    borderBottomWidth: 1,
    borderBottomColor: '#E7E7E9',
  },
  selectedTableRow: {
    paddingLeft: 10,
    paddingRight: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F3F4',
    height: 61,
    borderBottomWidth: 1,
    borderBottomColor: '#E7E7E9',
  },
  tableHeader: {
    paddingLeft: 10,
    paddingRight: 10,
    paddingBottom: 20,
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#E7E7E9',
  },
  numberColumn: {
    flexDirection: 'row',
    flex: 0.15,
    marginRight: 20,
  },
  checkbox: {
    marginLeft: 27,
    justifyContent: 'center',
  },
  nameColumn: {
    flex: 0.4,
    marginRight: 20,
  },
  priceColumn: {
    flexDirection: 'row',
    flex: 0.15,
    marginRight: 20,
  },
  amountColumn: {
    flex: 0.12,
  },
  totalPriceColumn: {
    marginLeft: 16,
    flexDirection: 'row',
    alignItems: 'center',
    flex: 0.15,
    justifyContent: 'space-between',
  },
  tableItem: {
    lineHeight: 28,
    fontSize: 18,
    fontFamily: 'System',
  },
  mainFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 56,
    backgroundColor: '#F3F3F4',
  },
  mainFooterItem: {
    fontSize: 24,
    lineHeight: 28,
    color: '#00B5B9',
  },
  deleteButton: {
    alignSelf: 'flex-end',
  },
  discountContainer: {
    marginLeft: 5,
  },
  discountItem: {
    position: 'absolute',
    top: -6,
    color: '#FF1414',
    fontSize: 14,
    lineHeight: 28,
    fontWeight: '500',
    fontStyle: 'italic',
  },
  categoriesContainer: {
    overflow: 'visible',
    height: '40%',
    marginTop: 18,
    borderBottomColor: '#E7E7E9',
    borderBottomWidth: 1,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 1,
    shadowRadius: 50,
  },
  categoriesHeader: {
    flexDirection: 'row',
    height: '15%',
  },
  categoriesInput: {
    paddingLeft: 11,
    height: '100%',
    flex: 0.9,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E7E7E9',
    borderRadius: 5,
  },
  categoriesList: {
    paddingLeft: 10,
    paddingBottom: 10,
    backgroundColor: 'transparent',
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
    overflow: 'visible',
  },
  category: {
    elevation: 10,
    overflow: 'visible',
    marginRight: '3%',
    marginBottom: 20,
    width: '30%',
    // height: 50,
    height: '13%',
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryTitle: {
    fontWeight: '700',
    fontSize: 18,
    color: '#00B5B9',
  },
  subcategory: {
    marginRight: '1%',
    marginBottom: 10,
    width: '24%',
    height: '13%',
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  subcategoryTitle: {
    fontWeight: '600',
    fontSize: 14,
    color: '#00B5B9',
  },
  scrollbar: {
    marginTop: 20,
    alignSelf: 'center',
    height: '90%',
    width: 17,
    backgroundColor: '#F3F3F4',
    overflow: 'hidden',
    borderRadius: 8,
    zIndex: 1,
  },
  formContainer: {
    height: '55%',
    marginTop: '3%',
  },
  smallButton: {
    height: '90%',
    maxWidth: '100%',
    width: 100,
    borderRadius: 5,
  },
  numberKeypad: {
    overflow: 'hidden',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F3F3F4',
    height: '100%',
    width: '50%',
  },
  key: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    backgroundColor: '#FFFFFF',
    borderColor: '#F3F3F4',
  },
  formButtons: {
    paddingLeft: '3.5%',
    width: '50%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignContent: 'space-between',
  },
  formButtonContainer: {
    width: '48%',
    height: '48%',
  },
  formButton: {
    maxWidth: '100%',
    width: '100%',
    height: '100%',
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#00B5B9',
    borderRadius: 5,
  },
  button: {
    height: 50,
    width: 170,
    borderRadius: 5,
  },
  whiteButton: {
    height: 50,
    width: 170,
    borderRadius: 5,
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#00B5B9',
  },
  buttonText: {
    fontSize: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  buttonBlueText: {
    fontSize: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
    color: '#00B5B9',
  },
  disabledGreyButton: {
    backgroundColor: '#999999',
  },
  disabledWhiteButton: {
    borderColor: '#999999',
  },
  disabledText: {
    color: '#999999',
  },
});

export const cashCounter = StyleSheet.create({
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: '10%',
  },
  divider: {
    marginTop: 10,
    marginRight: -30,
    marginLeft: -30,
    borderBottomWidth: 1,
    borderColor: '#E7E7E9',
  },
  countTitle: {
    fontSize: 18,
  },
  headerAmount: {
    marginTop: 18,
    fontSize: 18,
    fontWeight: '700',
  },
  paperBill: {
    width: 179,
    height: 322,
  },
  cashButton: {
    width: 160,
    height: 40,
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#E7E7E9',
    borderRadius: 5,
    maxWidth: 200,
    shadowColor: 'rgba(0, 0, 0, 0.05)',
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 1,
    shadowRadius: 20,
  },
  modalTitle: {
    width: 316,
    textAlign: 'center',
    fontSize: 24,
    fontWeight: '700',
    alignSelf: 'center',
    marginBottom: 48,
    lineHeight: 33.6,
  },
});

export const transactions = StyleSheet.create({
  container: {
    width: 375,
    alignSelf: 'center',
    backgroundColor: 'white',
    paddingTop: 52,
    paddingBottom: 73,
  },
  title: {
    fontSize: 18,
    fontWeight: '500',
  },
  card: {
    width: 335,
    backgroundColor: 'white',
    paddingTop: 10,
    paddingHorizontal: 10,
    borderRadius: 5,
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.8,
    shadowRadius: 6,
  },
  closeButton: {
    marginLeft: 42,
    marginRight: 8,
    backgroundColor: 'transparent',
    width: 16,
    height: 16,
  },
  deleteButton: {
    backgroundColor: 'transparent',
  },
  detailsButton: {
    alignItems: 'center',
    width: 68,
    paddingHorizontal: 0,
    backgroundColor: 'transparent',
  },
  cardTitle: {
    textTransform: 'uppercase',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 10,
  },
  cardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F3F3F4',
    paddingTop: 8,
    paddingBottom: 7,
    paddingHorizontal: 10,
    marginLeft: -10,
    marginRight: -10,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },
  cardFooterText: {
    fontSize: 18,
    fontWeight: '700',
  },
  arrowUp: {
    transform: [{ rotate: '180deg' }],
  },
  listHeaderItem: {
    fontSize: 10,
    color: '#575F6E',
  },
  listRow: {
    flexDirection: 'row',
    padding: 10,
    borderColor: '#E7E7E9',
    borderTopWidth: 1,
  },
  endDayListRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  divider: {
    marginBottom: 4,
    marginHorizontal: 4,
    alignSelf: 'flex-end',
    height: 1,
    flex: 1,
    backgroundColor: '#E7E7E9',
  },
  listTitle: {
    fontSize: 16,
    fontWeight: '500',
    textTransform: 'uppercase',
  },
  listItem: {
    fontSize: 16,
    color: '#575F6E',
  },
});

export default {
  common,
  component,
  scene,
  colors,
};
